export const CATEGORIES = [
  'Baking & Cake Decoration',
  'Photography & Videography',
  'Programming & Web Dev',
  'Fitness & Wellness',
  'Music & Instruments',
  'Languages',
  'Art & Painting',
  'Fashion & Design',
  'Cooking & Culinary Arts',
  'Beauty & Makeup',
  'Business & Entrepreneurship',
  'Marketing & Social Media',
  'Writing & Content Creation',
  'Dance & Performing Arts',
  'Sports & Coaching',
  'Finance & Accounting',
  'Personal Development',
  'Home & Garden',
  'Technology & IT',
  'Crafts & DIY',
];
