import '@testing-library/jest-dom/vitest';
import { vi } from 'vitest';

process.env.NODE_ENV = 'test';
process.env.DATABASE_URL = 'postgresql://test:test@localhost:5432/vuka_test';
process.env.REDIS_URL = 'redis://localhost:6379';
process.env.JWT_ACCESS_SECRET = 'test-access-secret-at-least-32-chars-long!!';
process.env.JWT_REFRESH_SECRET = 'test-refresh-secret-at-least-32-chars-long!';
process.env.JWT_ISSUER = 'vuka-test';
process.env.JWT_ACCESS_EXPIRY = '15m';
process.env.JWT_REFRESH_EXPIRY = '7d';
process.env.MPESA_ENV = 'sandbox';
process.env.MPESA_CONSUMER_KEY = 'test-key';
process.env.MPESA_CONSUMER_SECRET = 'test-secret';
process.env.MPESA_PASSKEY = 'test-passkey';
process.env.MPESA_SHORTCODE = '174379';
process.env.MPESA_B2C_SHORTCODE = '600000';
process.env.MPESA_B2C_INITIATOR_NAME = 'apitest';
process.env.MPESA_B2C_SECURITY_CREDENTIAL = 'test-credential';
process.env.MPESA_IP_WHITELIST = '196.201.214.200,196.201.214.206';
process.env.R2_ACCESS_KEY_ID = 'test-r2-key';
process.env.R2_SECRET_ACCESS_KEY = 'test-r2-secret';
process.env.R2_BUCKET_NAME = 'vuka-test';
process.env.R2_ACCOUNT_ID = 'test-account';
process.env.R2_PUBLIC_URL = 'http://localhost:9000';
process.env.NEXT_PUBLIC_APP_URL = 'http://localhost:3000';
process.env.ENCRYPTION_KEY = 'test-encryption-key-32-bytes-long!!';
process.env.SMTP_HOST = 'localhost';
process.env.SMTP_PORT = '587';
process.env.SMTP_USER = 'test';
process.env.SMTP_PASS = 'test';
process.env.SMTP_FROM = 'test@vuka.com';
process.env.SENTRY_DSN = '';
process.env.PAYOUT_2FA_MAX_ATTEMPTS = '5';
process.env.PAYOUT_2FA_WINDOW_MINUTES = '60';
process.env.PAYOUT_2FA_RESEND_COOLDOWN_SECONDS = '60';
process.env.NEXT_PUBLIC_SENTRY_DSN = '';
