export declare const env: {
    NODE_ENV: "development" | "production" | "test";
    DATABASE_URL: string;
    REDIS_URL: string;
    NEXT_PUBLIC_SUPABASE_URL: string;
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
    SUPABASE_SERVICE_ROLE_KEY: string;
    CSRF_SECRET: string;
    ENCRYPTION_KEY: string;
    EMAIL_HOST: string;
    EMAIL_PORT: number;
    EMAIL_USER: string;
    EMAIL_PASS: string;
    EMAIL_FROM: string;
    MPESA_CONSUMER_KEY: string;
    MPESA_CONSUMER_SECRET: string;
    MPESA_PASSKEY: string;
    MPESA_SHORTCODE: string;
    MPESA_B2C_SHORTCODE: string;
    MPESA_B2C_INITIATOR_NAME: string;
    MPESA_B2C_SECURITY_CREDENTIAL: string;
    MPESA_ENV: "production" | "sandbox";
    MPESA_IP_WHITELIST: string;
    R2_BUCKET_NAME: string;
    NEXT_PUBLIC_APP_URL: string;
    NEXT_PUBLIC_API_URL: string;
    BULLMQ_PREFIX: string;
    RATE_LIMIT_MAX: number;
    RATE_LIMIT_WINDOW_MS: number;
    AUTH_RATE_LIMIT_MAX: number;
    AUTH_RATE_LIMIT_WINDOW_MS: number;
    PAYOUT_RATE_LIMIT_MAX: number;
    PAYOUT_RATE_LIMIT_WINDOW_MS: number;
    ADMIN_RATE_LIMIT_MAX: number;
    ADMIN_RATE_LIMIT_WINDOW_MS: number;
    MAX_UPLOAD_SIZE: number;
    MAX_VIDEO_UPLOAD_SIZE: number;
    ALLOWED_MIME_TYPES: string;
    MAINTENANCE_MODE: "true" | "false";
    DISABLE_SIGNUPS: "true" | "false";
    REQUIRE_EMAIL_VERIFICATION: "true" | "false";
    LOG_LEVEL: "error" | "debug" | "info" | "warn";
    CORS_ORIGINS: string;
    MPESA_CALLBACK_URL?: string | undefined;
    MPESA_B2C_RESULT_URL?: string | undefined;
    MPESA_B2C_TIMEOUT_URL?: string | undefined;
    R2_ACCESS_KEY_ID?: string | undefined;
    R2_SECRET_ACCESS_KEY?: string | undefined;
    R2_ENDPOINT?: string | undefined;
    R2_PUBLIC_URL?: string | undefined;
    SESSION_ENCRYPTION_KEY?: string | undefined;
    SENTRY_DSN?: string | undefined;
    CSP_REPORT_URI?: string | undefined;
};
